### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Yeji-Jung** [Yeji-Jung/Hi#1]
1. 며칠간 코드를 작성하다보니 class, id를 어떻게 사용해야 적절한지 감이 오기 시작함. 
그런데 아직도 태그를 적절히 묶어 최대한 간단하게 코드를 짤 수 있는 방법을 잘 알지 못하겠음. 
현재 중복되는 코드 작성이 많아 더 공부해야 할 것 같음.

2. #main1 안에 또 다른 div를 추가하려고 하니 좌측정렬부터 item이 시작되지 않고 그 전 item 바로 밑에 생성됨. 
어떻게 해결해야할 지 몰라 우선  main태그를 한 개 더 추가하고  #main2라고 붙임 :(

3. 사이트 크기를 축소할 때 container에 있는 items도 container의 크기에 맞게 축소되게 하고 싶음.
이건 고민하면 나올 것 같긴 함.

**Comment by daehwan0307** [comment]
오늘은 공부 안하시나요..?
